services:
  gatus:
    restart: always
    image: ghcr.io/twin/gatus:v5.30.0
    container_name: gatus
    ports:
      - 8080
    volumes:
      - $DOCKER_VOL/gatus/config:/config
      - $DOCKER_VOL/gatus/data:/data
    depends_on: []
    environment:
      - GATUS_CONFIG_PATH=/config
