services:
  adguardhome:
    restart: unless-stopped
    image: adguard/adguardhome:v0.107.66
    container_name: adguardhome
    ports:
      - 81:80/tcp
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - $DOCKER_VOL/adguardhome/work:/opt/adguardhome/work
      - $DOCKER_VOL/adguardhome/config:/opt/adguardhome/conf
