services:
  wud:
    image: ghcr.io/getwud/wud:8.1.1
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/getwud/wud/releases/tag/$${major}.$${minor}.$${patch}
